# Generated by Django 3.2.7 on 2021-09-24 19:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=cloudinary.models.CloudinaryField(default='badgerz/image/upload/v1632511355/jellu_bmu8g6.jpg', max_length=255, verbose_name='image'),
        ),
    ]
